name: Docker Compose CI/CD

on:
  push:
    branches:
      - main

jobs:
  docker-compose-build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Create .env file
      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" | base64 --decode > .env

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build services with docker-compose
      - name: Build Docker Compose services
        run: |
          docker compose build

      # Tag images for the specific Docker Hub repository
      - name: Tag images
        run: |
          docker tag $(docker images --format "table {{.Repository}}:{{.Tag}}" | grep -v REPOSITORY | head -1) luongnguyenminhan/enteviu:latest

      # Push images to Docker Hub
      - name: Push images to Docker Hub
        run: |
          docker push luongnguyenminhan/enteviu:latest

      # Test the services (optional)
      - name: Test services
        run: |
          docker compose up -d
          sleep 30
          docker compose ps
          docker compose down
